# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: redis
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: redis
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 25